-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Oct 22, 2022 at 07:48 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kite_bd`
--

-- --------------------------------------------------------

--
-- Table structure for table `customer`
--

CREATE TABLE `customer` (
  `Customer Name` varchar(30) NOT NULL,
  `Customer Address` varchar(30) DEFAULT NULL,
  `Customer Mobile` varchar(20) NOT NULL,
  `Customer Email` varchar(30) DEFAULT NULL,
  `Customer Receipt` text DEFAULT NULL,
  `ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `customer`
--

INSERT INTO `customer` (`Customer Name`, `Customer Address`, `Customer Mobile`, `Customer Email`, `Customer Receipt`, `ID`) VALUES
('Robin', 'ctg.', '12345678901', 'robin@gmail.com', '*******************KITE-Receipt****************\nCustomer Name : Robin Address : ctg.\nMobile No : 12345678901 Email : robin@gmail.com\n------------------------------------------------------------- \nProducts Name : Rapoo V500 PRO Keyboard \nModel No : V500 PRO\nQuantity : 1\nPrice :                                                    3400 TK\n------------------------------------------------------------- \nDiscount (-) :5%	170		3230 TK\nWarranty : 2 years\nVAT(+) :10%	161		3391 TK\n------------------------------------------------------------- \nTotal :                                                    3391 TK\n------------------------------------------------------------- \n\n		 Bill generated by\n				 KITE Software\n', 9),
('Robin', 'ctg.', '12345678901', 'robin@gmail.com', '*******************KITE-Receipt****************\nCustomer Name : Robin Address : ctg.\nMobile No : 12345678901 Email : robin@gmail.com\n------------------------------------------------------------- \nProducts Name : Rapoo V500 PRO Keyboard \nModel No : V500 PRO\nQuantity : 1\nPrice :                                                    3400 TK\n------------------------------------------------------------- \nDiscount (-) :5%	170		3230 TK\nWarranty : 2 years\nVAT(+) :10%	161		3391 TK\n------------------------------------------------------------- \nTotal :                                                    3391 TK\n------------------------------------------------------------- \n\n		 Bill generated by\n				 KITE Software\n', 10),
('imon', 'khulna', '01234567890', 'imon@gmail.com', NULL, 11),
('imon', 'khulna', '12324556', 'imon@gmail.com', '*******************KITE-Receipt****************\nCustomer Name : imon Address : khulna\nMobile No : 12324556 Email : imon@gmail.com\n------------------------------------------------------------- \nProducts Name : A4Tech FG14 FSTYLER 2.4G \nModel No : FG14 FSTYLER\nQuantity : 1\nPrice :                                                    750 TK\n------------------------------------------------------------- \nDiscount (-) :5%	37		713 TK\nWarranty : 2 years\nVAT(+) :10%	35		748 TK\n------------------------------------------------------------- \nTotal :                                                    748 TK\n------------------------------------------------------------- \n\n		 Bill generated by\n				 KITE Software\n', 12),
('MD. Imon', 'Khulna', '01234567890', 'xyz@gmail.com', '*******************KITE-Receipt****************\nCustomer Name : MD. Imon Address : Khulna\nMobile No : 01234567890 Email : xyz@gmail.com\n------------------------------------------------------------- \nProducts Name : A4Tech FG14 FSTYLER 2.4G \nModel No : FG14 FSTYLER\nQuantity : 1\nPrice :                                                    750 TK\n------------------------------------------------------------- \nDiscount (-) :4%	30		720 TK\nWarranty : 12 months\nVAT(+) :10%	28		748 TK\n------------------------------------------------------------- \nTotal :                                                    748 TK\n------------------------------------------------------------- \n\n		 Bill generated by\n				 KITE Software\n', 13);

-- --------------------------------------------------------

--
-- Table structure for table `offer`
--

CREATE TABLE `offer` (
  `Category` varchar(20) DEFAULT NULL,
  `Products Name` varchar(30) DEFAULT NULL,
  `Model No` varchar(30) DEFAULT NULL,
  `Offer package` varchar(30) NOT NULL,
  `Discount` int(20) DEFAULT NULL,
  `Price` int(20) DEFAULT NULL,
  `Quantity` int(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `offer`
--

INSERT INTO `offer` (`Category`, `Products Name`, `Model No`, `Offer package`, `Discount`, `Price`, `Quantity`) VALUES
('Ram', 'Adata 4 GB Desktop Ram', '4GB DDR4 2666', '1x 4gb ddr4 ram', 74, 1776, 1),
('monitor', 'WALTON  21.45\" FHD LED ', 'WD215V05', '1x WD21505 Monitor', 1942, 11008, 1),
('Mouse ', 'A4Tech FG14 FSTYLER 2.4G ', 'FG14 FSTYLER', '4x FG14 Mouse Offer', 450, 2550, 4);

-- --------------------------------------------------------

--
-- Table structure for table `others`
--

CREATE TABLE `others` (
  `Warranty` varchar(20) DEFAULT NULL,
  `Discount` int(11) NOT NULL,
  `VAT` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `others`
--

INSERT INTO `others` (`Warranty`, `Discount`, `VAT`) VALUES
('1 months', 1, 1),
('2 months', 2, 2),
('3 months', 3, 3),
('6 months', 4, 4),
('12 months', 5, 5),
('2 years', 6, 6),
('3 years', 7, 7),
('4 years', 8, 8),
('5 years', 9, 9),
('6 years', 10, 10),
('7 years', 11, 11),
('8 years', 12, 12),
('9 years', 13, 13),
('10 years', 14, 14),
('12 years', 15, 15),
('15 years', 20, 20),
('', 25, 25),
(NULL, 30, 30),
(NULL, 35, 35),
(NULL, 40, 40);

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `Id` int(11) NOT NULL,
  `Products Name` varchar(50) NOT NULL,
  `Model No` varchar(20) NOT NULL,
  `Series Number` varchar(20) NOT NULL,
  `Category` varchar(20) NOT NULL,
  `Price` int(20) NOT NULL,
  `Quantity` int(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`Id`, `Products Name`, `Model No`, `Series Number`, `Category`, `Price`, `Quantity`) VALUES
(1, 'A4Tech FG12', 'FG12 FSTYLER', '100C001', 'Mouse ', 230, 16),
(3, 'A4TECH FG10 Wireless Mouse', 'FG10', '100C003', 'Mouse', 720, 10),
(4, 'A4TECH OP-720 Wired Mouse', 'OP-720', '100C002', 'Mouse', 350, 13),
(5, 'Rapoo V500 PRO Keyboard ', 'V500 PRO', '100C011', 'Keyboard ', 3400, 4),
(6, 'Adata 4 GB Desktop Ram', '4GB DDR4 2666', '100C021', 'Ram', 1850, 3),
(7, 'WALTON  21.45\" FHD LED ', 'WD215V05', '100C101', 'monitor', 12950, 6),
(8, 'G6400 10th gen Coffee', 'Intel Pentium Gold G', '100CM111', 'Processor', 6500, 4),
(9, 'Gigabyte X570S UD AMD', 'X570S UD', '100CM120', 'Motherboard', 23000, 4),
(10, ' SSD220Q 2TB 2.5\' SATA SSD', 'TS2TSSD220Q', '100M20S', 'SSD', 19500, 5),
(11, 'A4Tech FG14 FSTYLER 2.4G ', 'FG14 FSTYLER', '100C0011', 'Mouse ', 750, 24);

-- --------------------------------------------------------

--
-- Table structure for table `statistics`
--

CREATE TABLE `statistics` (
  `Total Amount` int(11) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `statistics`
--

INSERT INTO `statistics` (`Total Amount`, `id`) VALUES
(226, 1),
(3230, 2),
(221, 4),
(713, 5),
(720, 6);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `ID` int(11) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `EMAIL` varchar(30) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL DEFAULT 'NULL'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`ID`, `NAME`, `EMAIL`, `PASSWORD`) VALUES
(1, 'imon01', 'imon@gmail.com', '123456789'),
(2, ' imon02', 'imon0202@gmail.com', 'imon0202'),
(3, 'imon03', 'imon0303@gmail.com', 'imon0303'),
(4, 'Mr.abcd', 'abcd@gamil.com', 'abcd1234'),
(5, 'rezwan', 'abc@gmail.com', '12345678'),
(6, 'saiket', 'saiket@gamil.com', '12345678');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `customer`
--
ALTER TABLE `customer`
  ADD PRIMARY KEY (`ID`);

--
-- Indexes for table `offer`
--
ALTER TABLE `offer`
  ADD PRIMARY KEY (`Offer package`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `statistics`
--
ALTER TABLE `statistics`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `customer`
--
ALTER TABLE `customer`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `statistics`
--
ALTER TABLE `statistics`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
